name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
       mongodb-version: [4.0, 4.4]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Restore dependencies
      run: |
        cd tests
        dotnet restore
    - name: Build
      run: |
        cd tests
        dotnet build --no-restore
    - name: Test
      run: |
        cd tests
        dotnet test --no-build --verbosity normal
